---
title: "Merkkejä peräkkäin"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

---

<br>
<br>
<br>
<br>

## Tämä on jotain uutta, en tiedä mitä

<br>
<br>
<br>
<br>


#### Vuonisto

Kreppipaperin läpi kuultavat joet.\
Kulutuksen silittämät kumpareet, eroosion karhentamat kivet\
Uomia ja vuonoja liikuttavat voimat jaksavat hämmästyttää minua\
Kuka liikuttaa liikuttajaa?

Voisin sukeltaa maan keskipisteeseen, kaukaisimman aurinkokunnan kaukaisimmalle planeetalle \
ja en ymmärtäisi\
mitä oman napani ympärillä tapahtuu.

<br>

---

<br>

#### Nimetön


Tähän minulla ei ole muita sanoja kuin, että\
Olisitko aina mun?

Minulle maistuisi kyllä

<br>

---

<br>

#### Pyhä asuu pimeässä

Pyhä asuu pimeässä. Se koskettaa minua, painaa, kieputtaa.\
Olen hauras, olen altis; Pimeys saa vallata minut. 

Pimeyden turvin saan lähestyä ja loitota kuin liekki. Ja minä saan vallata ja valloittaa, elämöidä.\
Minua voi paeta -- ole hyvä -- mutta minä en pakene.

Pyhä asuu lämpimässä, siellä missä on hyvä olla. Missä on kaikki maailman aika ja vielä kymmenen minuuttia -- riittävästi. Tämä riittää minulle.

Pyhä asuu siellä, missä kuulen vain oman hengitykseni ja verisuonieni pulputuksen. Sellaisessa hiljaisuudessa, jossa huomaan, että hiljaisuutta ei ole.

Pyhä asuu sinussa. Haluan sinuun.

Pyhä asuu minussa, nyt.

<br>

---

<br>

#### Valovoima

Sinä olet jykevä kone. Sinä tarvitset nämä liekit, jotta pääset liikkeelle. Kun pääset, olet voima, jota ei voi pysäyttää.

Minä olen kolibri. Tämä valo valuu minuun kuin nektari liian pieneen astiaan. 

Kuplittaa\
Into ei mahdu minuun ja se ei ole ilahduttavaa. 

<br>

---

<br>

## Vihasaaga

<br>
<br>
<br>
<br>


#### Ei kyllä

Ei kiitos lähiöiden putkitalojen virralle\
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;vieraan lapsen huudoille\
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ei \
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pyynnöille, joita en ole koskaan lunastamassa takaisin
		
Sydämeni ei\
ole enää kaupan, ei halvalla, ei edes ilmaiseksi.\
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ei enää sinulle.

Sanoin ei\
Eikä mitään ollut tilalla\
Sanoin ei, sillä tyhjyys on parempi kuin mitä me olimme.

Joku päivä\
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tähän tyhjyyteeni kasvaa kyllä
	
jotakin kaunista ja omaa

<br>

---

<br>

#### Unohdettusi

Olen poissa ja sinä\
et edes tiedä\
sitä tai tätä tai muutakaan\
koska olen poissa

Olen poissa mutta minä\
minä tiedän missä sinä olet\
olet siellä ja täällä\
yhtä aikaa\
olet minun ja\
et todellakaan

Aina valmiina, aina\
sanon kyllä, nytkin\
vaikka et pyydä\
Mikset pyydä?

Olen poissa ja sinä\
olet \
ja sinä olet minulle\
minun ainoa tapani olla olemassa

Olen poissa ja en\
Tiedä sinua\
ehkä huomenna\
olen sinullekin\
Olen

Ehkä huomenna\
minäkin unohdan\
Ja olen

<br>

---

<br>

#### Teekutsut

Olet bergamotti \
kanelipullarouva

Sinä laulat onnen taloon\
Ja kas\
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;vain \
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Onni jää

Siksi en kai tullut\
toimeen kanssasi

<br>

---

<br>

#### Riepu

Kohta käy köpelösti.

Käyn siihen lepäämään, käärin itseni äitini tekemään täkkiin. \
vaikka\
raajani palelevat pieneksi käyneen peiton alla.\
Ei haittaa\
Tämä riittää.

Tilkuttu sydämeni ei ole enää paikalla\
kun isku käy\
Se on kääritty talteen\
pellavaisiin liinoihin

<br>

---

<br>

#### MeNaiset

Hyvät naiset & kaikki\
perseenne renkaisiin tunkijat\
käymälässä istualtaan kusijat.\
Tai muutkin, mutta siitä tietoiset, että tässä huoneessa ainakin joku joskus myös istuu. 

Minulla on parempaakin tekemistä, \
kuin pyyhkiä huolimattomuutesi sileiltä poskiltani. \
Ei paljon, mutta sen verran.

Odotin teiltä parempaa.

<br>

---

<br>

#### Suru&Viha

Sinä olet hidas, minä nopea\
Hiljaisuutesi aikana ehdin ajatella kaksitusinaa asiaa ja tehdä niistä kolme. Joista vähintään kaksi on väärää.\ Kertaalleen anon kaikkea\
Mitä sinä teet?

Vuosikymmeneen lasken kanssasi.\
Yksinäisyys kanssasi, yksinäisyys ilman\
kahdenkesken kukoistamme, niin muistelen\
En taida jaksaa laskea enempää, en muista enempää.

Tiedätkö, kuinka vaikeaa on olla vihainen surevalle?\
Huomaan oppivani hurjaa vauhtia.

<br>

---

<br>

#### Puolivihainen

Mä vihaan naisia\
Vittu vanhentunut virsi\
Mut ne ja me tekee sen nii helpoksi\
Että en voi muuta kuin laulaa: Totisesti!

Mä vihaan tekopyhiä, uhriutuvia naisia\
Aikansa marttyyrejä\
Kuunnellaan tunteita ja sallitaan kaikki\
Paitsi viha, mustasukkaisuus ja kaikki kova\
Ja ruma\
Kaikki paitsi kiva\
Ihan kiva\
Sivistynyt kaksihaarainen kieli\
Peittää kakaramaisuuden terapiapuheen alle\

Mä vihaan pieniä, sievästi tanssivia naisia. Mukavia kitkattomia naisia.\
Kohteliaita hiljaisia katseita ja vielä hiljaisempia sanoja. Niitä, jotka ei koskaan tee mitään, mistä pitäisi joutua pyytämään anteeksi. Ja tulevat näkymättömyydellään pyytäneeksi anteeksi kaikesta. 

Vihaan kun se toimii. Toimiiko se? Valitsinko väärin, silloin joskus, kun halusin olla jotain muuta. Kun ajattelin, että en kykene olemaan muuta kuin muuta.\
Mä vihaan kun se ei toimi. Kun Miehet katsoo teitä, niin ku mä katson. Minua? Vihaan, kun teen itsestäni niin vähän kuin mahdollista, jotta ei minua. Nuolen sotilaiden maihinnousukengät kiiltäväksi ja samalla kiillotan omanikin. Vihan oikeutus on aina ollut helpompaa kuin häpeän ja kateuden.

Kyllä, vihaan myös miehiä, mutta se ei ole nyt tärkeää.

Oleellista on muoto: on tai ei. Niissä on tai ei. Se on ja sen olemisen ongelmointi kiinteyttää sen olemista. Ja kun haluaisin vaan, että kaikki lilluu ja kelluu ja hyllyy. Ei-oo. Sulaa, haihtuu ja kohoaa. Ehkä sieltä näkyisi jotain uutta.

<br>

---

<br>

#### Näytön paikka

Milloin huomasit ensimmäisen kerran olevasi yksin?
Nyt huomaat sen metrossa päivittäin. Vastapäisellä laiturilla. Kotisi sohvalla. Makuuhuoneessa. Vilkkuvat valot ovat imaisseet heidät kaikki.

Ne eivät vieneet läheisiäsi yksitellen, vaan rysäyksellä. Mutta sinulla kesti huomata se. Niinhän sanottiin romaaneistakin, lohdutit itseäsi. Ja pesukoneista, elokuvista, autoista, pornosta, e-pillereistä. Juuttisäkkiin palaaminen tuntui juntilta, ajattelit.

Kyselit, huomautit ja epäilit. Hyppäsit junasta ja hyppäsit kyytiin uudestaan. Nyt roikut ikkunasta osaamatta jäädä pois tai nauttia edes vaunun lämmöstä.

Voit olla yksin yksin tai muiden kanssa yksin. Ravintolavaunusta voit valita makaronilaatikkoa tai maksalaatikkoa.

<br>

---

<br>

#### Käytöstapoja

Käytöstapoja, vaaditte. Vaaditte, te sääntöjen vartijat. Käytöstavat on moraalinen koodistonne.
Ja minä pahoittelen, nöyrästi pahoittelen. Niin, muistan minäkin, mitä koulussa opetettiin. Muistan, että pääsee helpommalla, jos katsoo vielä alemmas kuin sinua vanhemmat sinua. Muistan, että ylpeys on suurin synti heti köyhyyden jälkeen. Muistan, kuinka helppoa oli vaieta ja lopulta ääni minussa vaikeni myös.

En pääse liikkumaan. En pääse täältä pois.

<br>

---

<br>

#### LED

Miten sinua ei satuta tämä piinaava valo? Katse, joka ei ole koskaan ymmärtänyt elämästä mitään valvoo näitä kiviä. Heittimet kuin sireenit karkottavat pyhän pois. Värit kuolevat sen syleilyssä. Taistelen vastaan sulkemalla luomeni sieluni verhoksi, mutta valo pistää läpi enkä pääse pakoon.

Kuka elämästä vieraantunut ja sille vihamielinen olento on päättänyt levittää nämä portit auki ja päästää sen voimat valloilleen? Kuka papereista elävä virkamies on lasittunein silmin lukenut kustannusarvioita ja kestävyystavoitteita ja päättänyt, että kaikki muu saa jäädä alle. Olitko se sinä? Olinko se minä?

Pyhä asuu pimeässä. Ei ihme, jos tämä levoton aika ei löydä rauhaa.

<br>

---

<br>

#### #vihanvoimalla

Tunteeni ovat jossain, ehkä työn alla. Ne möyrivät esiin kuin rikkaruohot; rumina ja sopimattomina. Kitken ne geometrisen kivipuutarhani tieltä.

Odotan sinulta jotain, mitä en itse jaksa antaa. Jopa saan. Silti olen lähinnä vihainen. Vihainen olen ollut ulos ja sisään, sisään ja ulos. Jotain teen väärin. Sinä teet aina jotain väärin.

Lämmitän katkeruuden hellalla kitkerän kaurapuuron. Syötän sen sinulle. Syljet sen takaisin naamalleni.

Vihani nukkuu huonosti. Kerään sen sipulit joka ikisestä kammarista ja kehdosta, joissa olen koskaan nukkunut. Kerään ne koriin, tuon ne korvakäytäviesi mehevään maaperään, sillä minussa ei kasva mikään. Se leviää kuin kielo. Haistelemme sen kukintoa yhdessä. 

Vien vihani lenkille. Huudatan sitä tiedemetsässä, tiedemenetelmin, tieteellisellä tarkkuudella. Se kumisee yksinäisyyttään, kuten tieteentekijälle kuuluukin. Se tietää, että kukaan ei tule tuloksista tietäväisemmäksi. Vastaantulija kysyy "tapahtuiko metsässä juuri murha?". Vastaan: "se olin vain minä".

<br>

---

<br>

#### Vihan historia

Et voi väittää, että en ole yrittänyt. Ensin olin hiljaa. Olin hiljaa kun äitini kaatoi itsensä ja mielipiteensä kolisten päälleni. Olin hiljaa ja käänsin televisiosta äänet kovemmalle. Olin hiljaa kun aikuiset katsoivat ääneti. Olin niin hiljaa, että lopulta sydämenikin kohisi kuin tyhjä kanava.

Sitten en ollut hiljaa ja ystäväni ja rakkaani kysyivät "kuinka kehtaat"? Ja niin kuvittelen että en kehtaa kunnes hiljaisuuteni käy äänekkääksi kuin koski. 

Vyöryn ja patoan.

<br>

---

<br>

#### HHHHHHHHH

Vajoan syvään pehmeyteen. Olen siinä suloisessa pisteessä, juuri ennen tiedottomuutta, jossa tiedän, että se tulee, mutta en ole vielä siellä. En halua venyttää sitä, vaikka se on paras tunne maailmassa. Silmäluomeni märkivät halusta unohtaa näkemänsä edes hetkeksi.

Klipnjaaa. Shiih shiih. Kuplomkhah khah khapmamp. 
	Shiuh shimp
	Shimpshimpshimp
	
	
 --  HHHHHH [M.] HHHHHHHHHHHH

shishim

Tap
	Taptap
	
TAPTAPTAP

-- hhhhhhhh
 
 Tiedän, että mahdollisuuteni karkasi minulta jo.  
 
 <br>
 
---
 
 <br>
 
#### Vihan historia vol 2. 

Mä haluaisin, että 30-vuotias Stalin kattois mua syvälle silmiin ja pyytäis seuraamaan. Mä paljastaisin vasemman rintani ja liehuttaisin hameestani tehtyä banderollia toisessa kädessä. Sen liepeisiin tarraisi vihaisten miesten kädet ja yhdessä me tuhon voimalla revittäisiin myös autoista maalit päältä.

Mä haluan tuhota. Haluan mäiskiä, tarrata, naarmuttaa, polttaa kiiltäväpintaisia autoja talojen pihalla, joissa on korkeat huoneet ja kulmikkaat erkkerit. Mä haluan, että kiiltäväpinta-autojenomistajia pelottais tulevaisuus yhtä paljon ku mua. Päivittäin. Öisin. Mä nukun huonosti niiden takia. Olis vaan reilua että ne nukkuis huonosti mun takia.

En ole kohtuuton. Mä voin ihan hyvin lopettaa autoihin. Jos pakenevat, saavat pyytää kyytiä Jeesuksen seuraajilta. Muussa tapauksessa katsovat tätä samaa maailmaa ja meitä. Mitä likasemmilta me näytetään, sitä enemmän me rumennetaan niiden katunäkymää.

Oikeesti mulla vois olla se auto. Joten mä oon varmaa enemmän "ne" kuin "me". Mut toisaalta, mulla ei oo. Joten jossain on tehty valintoja, minussa tai minulle.

Kilometrien korkuinen ja sienen muotoinen väkivallan uhka katosi. Tai ehkä se vain vaihtoi väriä. Joten mä en osaa muuta kuin kirjottaa.

<br>

---

<br>

#### Vanhentunut

Mua etoo

Imelä, pieni ja makea sana suussa. Käymisen aloittanut marja. Mä kutsun itteeni sillä vaan sillon ku on pakko. Kun alistan itseni siihen muottiin, mitä Yliopisto, Tori, Oikotie, Pankki, Perhe — mitä näitä tärkeitä instituutioita nyt onkaan — multa odottaa.

Kun sä kutsut mua niin, osaan kohdistaa vihan sinne, minne se kuuluu. 

Älä enää koskaan kutsua mua tolla nimellä, sanon — ennen kaikkea itselleni.

<br>

---

<br>

#### Rajoista
Jos kaiken tekemisensä vertaa seksitilanteeseen, aika nopeasti selviää, mitä haluaa tehdä ja mitä ei.

Ja argumentit, kuten  

"koska mun on pakko"  
"se ois helpompaa"  
"sit vältän riidat"  
"noku mä lupasin"  
"ei kai viime hetkellä voi perua"  
"entä jos se suuttuu mulle"  
"hirvee vaiva"  
"muuten en koskaan oo mitään"  
"tää ei riitä"  


rupee kuulostaa aika hupsuilta.

<br>

---

<br>

#### Ilkeys ja kauna

Ukkini opetti minulle joskus korttipelin nimeltä "Ilkeys ja kauna". En enää muista sen sääntöjä tai tarkoitusta. Pelaan sujuvasti siitä huolimatta.

Kauna on sitä, että haluaa, mutta kieltää sen itseltään. Ilkeys on sitä, kun syyttää siitä muita. Näin puhui Nietzsche.

Maailma on ruma ympärilläni ja minä vihainen kaunainen mutapallero. Tiedän, että näin ei tarvitsisi olla.

Olen haluton päästämään irti kaunastani. Samalla joudun päästämään irti turvasta, jonka hyveellisenä oleminen tuo. Jos ei enää syytä muita, on vaara joutua itse syytetyksi. Ja olla syyllinen syytöksiin. Vahvuutta olisi kantaa se. Vahvuutta, jonka ukkini ehkä osaisi opettaa, jos olisi elossa. Vahvuutta, jonka minä voisin oppia, jos minä olisin elossa.

Ecuadorissa oli nainen, joka koputti hauta-arkkuaan omissa hautajaisissaan. Ehkä koputuksen kuulee vasta kun kaikki ympärillä ovat hiljaa. Tai ehkä kuuntelu vaatii seurakseen surun, joka on vain yksi muoto rakkautta.

<br>

---

<br>

#### Mä vihaan sua.

Sanot sen kuin rakkaudentunnustuksen maankuorien paineen purskauttaessa lauseen ilmaan. Olen Pompeijin asukas, jähmettyneenä ikuiseen hämmästykseen. Jäljelle jää hitaasti valuvaa laavaa, joka kimmeltää tyrmäävässä kauneudessaan.

<br>

---

<br>

#### Lokki

Saastainen valkoinen parvi roskaruuan ympärille kokoontuneena. Niiden ahnaat silmät seuraavat lipuvia lihakimpaleita tarkkaillen, milloin voivat ottaa toisen omaa.  Ne repivät kääreitä ahnaasti, jättävät jälkeensä revityn silpun. Vievät tilan huudolla ja tulemalla liian lähelle. Turvaväli olematon, turvasana turha.

Pelkään. Enkä syyttä, olen kohdannut niiden kaltaisia monta. Alati hartiat jäykkänä varuillani, valmiina. Joskus olen joutunut käyttämään valmiuttani ja juossut pakoon kirkuen. Useimmiten selviän päänsäryllä.

Miksi toisille sallitaan väkivalta ja minulle ei? Ei edes puolustusmielessä, etukäteen? Haluan ampua alas mainokset, lokit, humalaiset, poliitikot, jotka vie rahat mun tililtä, ajatukset, jotka kylvävät samaa vihaa kuin mistä itse puhun.

<br>

---

<br>

## Pieni ja Toinen

<br>
<br>
<br>
<br>

#### Pieni ja Toinen  

Pieni oli tietenkin pienempi, mutta Toinen ei oikeastaan ollut sen toisempi kuin Pieni. Tosiaan, Toinen kerran jos toisenkin oli miettinyt kuinka vieras olio Pieni toisinaan oli. Kuinka kerta kaikkisen oma avaruutensa, jonka pimeyden poimuihin saattaisi kadota, jos Pieni ei ollut ohjaamassa, ja välillä silloinkin. Ehkä juuri pienen sokkeloisuuden tähden Toinen tunsi olonsa erityisen vahvaksi silloin, kun kykeni osoittamaan suunnan Pienen ollessa hukassa; varsinkin jos Pieni tätä toiselta pyysi. Näinä kertoina he olivat molemmat jättiläisiä. 

---

#### Talvi

Pieni ja Toinen kävelivät lumisella polulla lapanen lapasessa. Huurre tarttui Pienen poskipäiden mutaan ja Toisen viiksikarvoihin. 

-- Katso! Pieni osoitti toista ja kikatti. -- Sinun ripsesi ovat aivan valkoiset!

Toinen käveli itsensä ympäri, kurkisti jalkojensa lävitse, kainaloidensa alta ja käänsi vielä silmänsä niin taakse kuin osasi, niin että valkuaiset paistoivat. Kummallisen tanssinsa jälkeen hän sanoi:

-- Kaiken, mitä pyydän niin teen, jos vain suinkin pystyn, mutta silmieni näkemiseen en taivu. Taidan olla tulossa vanhaksi.

Toinen huokaisi suureellisen syvään ja Pieni taputti Toista myötätuntoisesti olkapäälle totinen ilme kasvoilla.

-- Vanhuus on ollut sinussa ja kauan ennen kuin tapasin sinut ja minä sentään olen tuntenut sinut aina. Ehkä oli vain aika, että sinä tapaat hänet myös. Mutta nyt on aika Toisen.

Ja sitten Pieni otti Toista taas kädestä, puristi lujaa ja alkoi juosta. Sillä mikään ei jätä aikaa taakseen kuten korvissa juokseva veri.

---

#### Avaruus

Lumi leijaili hiljalleen maahan, mutta sitä eivät Pieni ja Toinen huomanneet. Lapaset tippuivat eteisessä vettä omaan lammikkoonsa tip, tip, tip ja pipot ja lakit lojuivat lattialla avoimessa syleilyssä. Vaatteitaan matkien loikoivat myös Pieni ja Toinen. Toinen pyöritti Pienen niskavilloja sormenpäillään ja kysyi Pienen korvannipukalta:

-- Mitä sinä haluaisit kaikista mieluiten juuri nyt tehdä?

-- Haluaisin nähdä tähden syntyvän ja kuolevan, Pieni vastasi kääntäen katseensa Toiseen.

Ja niin Toinen veti Pienen lähimmän galaksin lähimpään alkavaan tuikkeeseen. Ulkopuolinen tarkkailija saattaisi sanoa siinä kestäneen tuhat vuotta tai silmänräpäyksen, mutta Pieni ei ulkopuolisten katseista piitannut. Tiet etäisyyksiin eivät koskeen olleet pitkästyttäviä Toisen kanssa.

---

#### Aika

Toinen puki Orionin vyön lanteilleen ja he ratsastivat Otavalla tunnetun ja tuntemattoman Avaruuden halki. He imivät sisäänsä autiutta Kuun pimeällä puolella, pulahtivat Caloriksen altailla Merkuriuksella ja kipusivat Luomisen Pilarien huipuille katsomaan loppua maailmankaikkeutta, maailmankaikkeuden loppua.

-- Nyt kun olen nähnyt maailmankaikkeuden, haluan nähdä ajankaikkeuden, sanoi Pieni Toiseen tarraten. Yhdessä he hyppäsivät Luomisen Pilarien ylimmästä huipusta suoraan keskisuuren mustan aukon lävitse, aivan kuten matkaoppaassa neuvottiin.

Ja he olivat taskussa, jossa valottomuus ei ollut pimeyttä ja lämmöttömyys ei ollut kylmyyttä. Koska ajalla ei ollut äärettömyydessään muotoa, puuttui kaikelta muultakin ääriviivat. Pieni oli Toinen ja Toinen Pieni. Tai he eivät kumpikaan olleet yhtä tai toinen toistaan toisempia. Ajatus oli yksi ja se oli hyvä. Kuinka pitkään? Se on mieletön kysymys ajan tuolla puolen. Mutta mieli hamuaa muutosta jopa äärettömässä hyvässä.

Yksi ajatuksista - jos yksiköistä tai edes ajatuksista saattoi puhua - oli kaipuu ajatusten vaihtoon. Siihen epätarkkuuteen, mitä toisen vieraus mukanaan tuo ja mikä pakottaa tutustumaan, etsimään, seikkailemaan. Tietäminen on loppujen lopuksi ja aikojen ajaksi melko tylsää, samaan tapaan kuin onnellisuuskin.

-- Mennään! Seurasi ajatus ja Pieni näki taas Toisen kaikessa toiseudessan ja Toinen ajan varjon liikkuvan Pienen karvojen yllä. 

-- Minun on ikävä sinua, sanoi Pieni ja kosketti Toisen kasvoja kuin yrittäen sulautua taas yhdeksi siinä tietenkään onnistumatta. Ja niin oli hyvä.

---

#### Tuuli

Pieni istui hytisten pesänsä nurkassa. Tämä kolo oli yleensä lämmin turva saalistajilta ja muilta ikävyyksiltä. Mutta tänään ovenraosta veti ja Ulkomaailma pyrki sisään sellaisella voimalla kuin vain loppusyksyn rajuilmat tapaavat. Kurkistusikkunan luukut vuotivat julman Tuulen sisälle. Se vinkui epätoivon lauseita Pienen korviin:

-- Taistele! Pakene! Puolustaudu! Valmistaudu! se haastoi Pientä ja ravisteli ovea karmeja myöten.

-- Turhaa kaikki! Jylisi Tuuli ja ui Pienen villojen sisään. Vaikka Pieni oli kerännyt kaikki omistamansa peitot suojakseen, marssi Viime niiden jokaisen lävitse ja asettui Pienen sisuksiin mukavasti kuin voittaja ainakin.

-- Turhaa kaikki, kaikui Pieni Tuulen sanat kivisille sienille ja katseli toimettomia tassujaan

Päivä ehti muuttua pimeydeksi ja yhä vain viima vinkui ja tassut eivät ottaneet tarttuakseen. Pienen pieni selkä tuntui jäykältä viileää valkeutta vasten ja pieni takapuli oli muuttunut alustakseen. Hetki hetkeltä raajat huusivat ja vatsa karjui voimalla ja lopulta lujempaa kuin tuulen vaativa humina.

Ja niin Pieni antoi vallan ruumiilleen, joka kantoi hänet keittiöön. Veltot tassut löysivät pimeässäkin aurinkoisempina päivinä kerätyt kätköt. Kappale, nimeltä Pieni, lipui kuivaan ja lämpimään ja laittoi Pienen valot kiinni. 

---

#### Kiire

Entä sitten toisaalla? Tunnista toiseen Toisen tassut vispasivat yhtä ja jalat vatkasivat heti perään toista. Voisi jopa sanoa, että Toinen oli niin toisaalla ettei ollut siellä ensinkään. 

Toinen puki ripeästi päälleen vakavat vaatteet, mutta unohti kaikessa kiireessä sydämensä lakanoiden laskoksiin. Olikohan Sattuma tehnyt kaupat Kohtalon kanssa kun yhtäällä täysin samanaikaisesti kuin toisaalla vaativat niin Pienen kuin Toisenkin jäsenet vallanvaihdosta. 

-- Liikkeelle! huusivat jäsenet Pien-yhtiössä.

-- STOP! Vaativat jäsenet taas Tois-osastossa.

Yksikköjen yhteisissä pikkujouluissa jäsenet jupisivat kilpaa ja olivat kaikki salaa sitä mieltä että toisen pomo oli kyllä parempi kuin oma.

---


#### Lupaus

-- Olen kyllästynyt tähän kylmyyteen, Pieni sanoi ja hyppäsi suoraan kevääseen. Mutta voi! Toinen oli jäänyt sydäntalveen eikä Pieni päässyt enää takaisin. Odottaminen on sentään helpompaa kun varpaita saattoi huljutella jäiden alta pakenevassa virrassa. Vesi oli tietenkin siihen aivan liian kylmää, mutta poskille satava valo sai unohtamaan sekä kylmän että kivun hetkeksi. 

Vihdoin löysi Toinenkin Kevään auringon ja Pienen sen säteiden sylistä. Pienen pakahtunut sydän muuttui solmuksi, kun hän näki jo matkan päästä hohkaavan kivun Toisen silmissä.

-- Olen etsinyt sinua kolosta, kannosta, lumesta, linnasta, taskusta, eilisestä, huomisesta ja joka päivästä niiden välillä löytämättä sinua.

Joka sanaa rytmitti rinnuksille putoava kirkas kyynel kuin jäinen helmi.

-- Mikset jäänyt? Toinen parahti. -- Tai ottanut mukaan?

Pieni ei voinut katsoa Toisen silmiin, jotka olivat syvät lammikot, joten hän katsoi niistä virtaavia puroja. Soliseville virroille hän kertoi: 

-- Sinä näytit niin kiireiseltä enkä halunnut lisätä yksinäisyyteni taakkaa harteillesi.

-- Sinun poissaolosi se oli murtaa minut alleen, Toinen sanoi hiljaa ja juuri hiljaisuus sai häpeän jyskyttämään Pienen kurkussa niin kipeästi. -- Minä tarvon ennemmin ikuisessa räntäsateessa sinä selässäni kuin enää koskaan ilman. Lupaatko että et enää koskaan katoa? Toinen kysyi ja ojensi kätensä lupauksen ja sovinnon tarjottimeksi.

Pieni mietti kaikkia mahdollisia paikkoja ja kaikkia mahdollisia tulevaisuuksia, niin kuin täytyy kun on antamassa lupauksen oikein tosissaan. Lopulta hän kaivoi taskustaan lankakerän, jonka toisen pään hän sitoi itseensä 

-- Minä pidän tämän pään, sinä saat loput, Pieni sanoi ja asetti kerän Toisen avoimelle kämmenelle. -- Niin kauan kuin tahdot, lupaan olla langan päässä.

Toinen laittoi Pienen kerän taskuunsa niin, että nauha sai juosta vapaana taskun suupieltä pitkin. Varmuuden vuoksi hän sitoi vielä toisen pään oman ranteensa ympäri. Jos aika tulisi, että Toisen pitäisi joko mennä mukana tai päästää irti, ainakin hän tietäisi milloin oli sen hetki. Mutta pieneen kerään mahtui paljon mittaa ja juuri nyt heillä oli nyt ja koko äärettömyys, mikä mahtuu hetkeen, jos siinä vain malttaa olla.

---

#### Peili

Toinen oli toisaalla -- ehkä naurutalossa toisen toisen kanssa -- ja Pieni tunsi itsensä hyvin pieneksi ja merkityksettömäksi. Pieni piiloutui peilitaloon, jossa hänen jokainen ajatuksensa heijastui alati kiihtyvänä kierteenä ikuisiin versioihin hänestä. Mustat säteet lävistivät hänet joka suunnalta, eikä auttanut vaikka hän juoksi yhä lujempaa ja yhä syvemmälle sokkeloisiin käytäviin.

Jostain Pieni kuuli Toisen naurun, ja se kaikui hänen kammioidensa seinistä metallisena, ivallisena. 

Ääni voimistui, eikä se ollutkaan HA HA HAA! vaan HU HU HUU? Kutsuva uu hukkui Pienen uupuneisiin uumoksiin. Jos Toinen todella välittäisi, hän huomaisi minut, Pieni tuumi ja oli vielä hiljempaa.

Pieni näki Toisen heijastuvan rinnalleen, mutta ei tuntenut mitään lähellään. Toinen näytti kylläkin -- jos mahdollista -- vielä eksyneemmältä kuin miltä hänestä tuntui, suu uun muotoisena jähmettyneenä kutsuun, johon ei tule vastausta. Tuo näky kosketti Pienessä jotain, joka purkautui kuin huomaamatta.

-- Katso nyt kuinka epämuodostunut olen! Pieni parkui.

Ja silloin Pieni tunsi Toisen posken poskellaan. Hän tunsi tämän lämmön selkäänsä ja raajojaan vasten kuin ympärilleen käärityn villaisen huovan. Toinen katsoi Pienen peilikuvaa tämän olan yli.

-- Etkö näe, että se on vääntynyt.

Ja totisesti, Toinen oli yhtä vinkuralla kuin hänkin samasta peilistä katsottuna.

Kas näin, Toinen sanoi, ja käänsi Pienen kohti omia kasvojaan, jossa Pieni näki kaksi pientä pyöreää peiliä. Niiden läpi ei näkynyt mitään muuta kuin Pieni joka oli Toinen joka oli Pieni joka oli Toinen, loputtomien heijastusten summana.

-- Mennään kotiin.

Tuhannet toisiaan kädestä pitävät Pienet ja Toiset siirtyivät peilistä toiseen, kunnes ei näkynyt enää mitään.

---
